In [26]:
import pandas as pd

In [27]:
df = pd.read_csv(r"C:\Users\frapu\Desktop\TableEmbeddingsWithGNNs\Datasets\testAB.csv")

In [29]:
df.shape

(4, 2)

In [32]:
df.dropna(axis=1,how='all', inplace=True)

In [33]:
df.shape

(3, 2)

In [10]:
df.iloc[0]

A    Luca_rossi the boss 92
B                      23.0
Name: 0, dtype: object

In [11]:
df.iloc[1]

A    Mario
B    345.0
Name: 1, dtype: object

In [12]:
df.iloc[2]

A    Valerio
B        NaN
Name: 3, dtype: object

In [13]:
df.iloc[3]

IndexError: single positional indexer is out-of-bounds

In [21]:
l = [0,1,2]
l

[0, 1, 2]

In [22]:
l[0:512]

[0, 1, 2]

In [23]:
l = [i for i in range(2048)]

In [24]:
max(l)

2047

In [25]:
max(l[0:512])

511

In [1]:
import pandas as pd

In [1]:
from embeddings import *

c:\Users\frapu\Anaconda3\envs\HPIMaster\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
df1 = pd.read_csv(r"C:\Users\frapu\Desktop\TableEmbeddingsWithGNNs\Datasets\testAB.csv")
#df = pd.read_csv(r"C:\Users\frapu\Desktop\TableEmbeddingsWithGNNs\Datasets\walmart_amazon-tableB.csv")
print('Starting')
df2 = pd.read_csv(r"C:\Users\frapu\Desktop\TableEmbeddingsWithGNNs\Datasets\fodors_zagats-master.csv")
bert_embedding_generator = Bert_Embedding_Buffer()
string_token_preprocessor = String_token_preprocessor()
print('Graph generation starts')
start = time.time()
g1 = Graph(df1, 'Table', bert_embedding_generator, string_token_preprocessor)

end = time.time()
print(f't_exec: {end-start}s')
print(f'number of embeddings: {g1.X.shape[0]}')
print('Graph generation starts')
start = time.time()
g2 = Graph(df2, 'Table', bert_embedding_generator, string_token_preprocessor)
end = time.time()
print(f't_exec: {end-start}s')
print(f'number of embeddings: {g2.X.shape[0]}')

gl = Graph_list()
gl.add_item(g1)
gl.add_item(g2)
gl.save(r"C:\Users\frapu\Desktop\TableEmbeddingsWithGNNs\Tests")



Starting


Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\frapu\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-d

Graph generation starts
Row: 0/3
t_exec: 1.822990894317627s
number of embeddings: 10
Graph generation starts
Row: 0/864
Row: 100/864
Row: 200/864
Row: 300/864
Row: 400/864
Row: 500/864
Row: 600/864
Row: 700/864
Row: 800/864
t_exec: 2.6639578342437744s
number of embeddings: 6053


In [3]:
gd = GraphDataset(directory_name=r"C:\Users\frapu\Desktop\TableEmbeddingsWithGNNs\Tests")

Empty sample_list created


In [4]:
gd.add_item((0,1,0.3))

In [5]:
len(gd)

1

In [9]:
s = gd[0]

In [7]:
e = EmbeddingGenerator()

In [11]:
e(s[0].X,s[0].edges).shape

torch.Size([128])

In [12]:
e(s[1].X,s[1].edges).shape

torch.Size([128])

In [13]:
s[2]

0.3

In [3]:
class test:
    def test():
        pass

In [8]:
t = test()

In [9]:
t.prova

AttributeError: 'test' object has no attribute 'prova'

In [11]:
try:
    not(t.prova)
except:
    print('updated prova')
    t.prova=5

In [2]:
import gensim.downloader as api

In [3]:
model = api.load('fasttext-wiki-news-subwords-300')

In [19]:
type(model['may'])

numpy.ndarray

In [21]:
import torch

In [29]:
torch.rand(100)

tensor([0.5386, 0.8531, 0.6390, 0.0187, 0.0480, 0.8659, 0.5062, 0.9115, 0.9067,
        0.7758, 0.5354, 0.0296, 0.8004, 0.1584, 0.3994, 0.9848, 0.5778, 0.2977,
        0.9672, 0.7102, 0.7066, 0.3659, 0.0319, 0.6083, 0.0279, 0.7886, 0.2789,
        0.4406, 0.2790, 0.5384, 0.7354, 0.0679, 0.7561, 0.5447, 0.9265, 0.3675,
        0.5519, 0.4432, 0.7307, 0.3088, 0.2435, 0.8187, 0.7165, 0.5511, 0.7885,
        0.0305, 0.0874, 0.2149, 0.3073, 0.5008, 0.5511, 0.5354, 0.4967, 0.2741,
        0.8523, 0.3856, 0.7732, 0.4448, 0.2872, 0.1715, 0.2130, 0.4620, 0.0399,
        0.3646, 0.2183, 0.1975, 0.8104, 0.9964, 0.9622, 0.0178, 0.3510, 0.4774,
        0.0062, 0.0074, 0.0309, 0.3019, 0.6122, 0.6209, 0.7348, 0.9019, 0.9303,
        0.3495, 0.7801, 0.1442, 0.1083, 0.9036, 0.7426, 0.6838, 0.7354, 0.5639,
        0.4512, 0.3233, 0.2404, 0.0555, 0.2883, 0.4828, 0.8138, 0.1792, 0.6381,
        0.9246])

In [31]:
torch.tensor(model['may']).shape

torch.Size([300])

In [1]:
from node_embeddings import *

c:\Users\frapu\Anaconda3\envs\HPIMaster\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
gen = FasttextEmbeddingBuffer()

Loading fasttext model, it will take 2/3 minutes
Model loaded


In [58]:
l = "cat dog duck luck"
gen('cat')

In [28]:
gen.n_embeddings

1

In [29]:
gen(l)

In [45]:
gen.n_embeddings

0

In [59]:
l = gen.pop_embeddings()

In [51]:
l.shape

torch.Size([1, 300])

In [56]:
gen.embeddings.shape

AttributeError: 'NoneType' object has no attribute 'shape'

In [60]:
l[0]

tensor([inf, -inf, inf, -inf, -inf, inf, inf, -inf, inf, inf, -inf, -inf, inf, -inf, -inf, inf, inf, -inf, inf, -inf, inf, -inf, inf, inf,
        inf, -inf, inf, inf, inf, inf, -inf, -inf, inf, inf, -inf, -inf, inf, -inf, -inf, -inf, inf, -inf, -inf, -inf, inf, inf, inf, inf,
        inf, -inf, inf, inf, inf, -inf, inf, -inf, -inf, inf, -inf, inf, -inf, -inf, inf, -inf, inf, inf, -inf, inf, -inf, -inf, inf, inf,
        inf, -inf, inf, inf, -inf, -inf, inf, -inf, inf, -inf, inf, inf, inf, -inf, -inf, inf, inf, inf, -inf, inf, -inf, -inf, inf, inf,
        inf, inf, inf, inf, inf, inf, inf, inf, -inf, -inf, -inf, inf, -inf, -inf, -inf, inf, inf, -inf, -inf, -inf, inf, inf, -inf, inf,
        -inf, inf, inf, -inf, inf, inf, -inf, -inf, -inf, inf, -inf, -inf, -inf, inf, -inf, -inf, -inf, inf, inf, -inf, -inf, inf, inf, -inf,
        -inf, -inf, inf, -inf, -inf, -inf, -inf, inf, inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, inf, -inf, inf, -inf, -inf, inf, inf,
        -inf, -inf, 

In [53]:
gen('lake blue')

In [54]:
gen.embeddings

tensor([[ 0.1417, -0.0665,  0.0294, -0.0054,  0.0601, -0.2388, -0.1346, -0.3108,
         -0.0226,  0.0270,  0.0815, -0.1351,  0.0647, -0.0543, -0.0556, -0.0770,
          0.1919, -0.0293,  0.0899, -0.0602,  0.0532, -0.0686, -0.0742,  0.1616,
         -0.0191, -0.1480, -0.0375,  0.1188,  0.0025,  0.0875, -0.0206,  0.0963,
          0.0830,  0.0317, -0.0097,  0.0113,  0.0815,  0.0515,  0.0598,  0.0118,
          0.1208, -0.3760, -0.0151, -0.0722,  0.1138, -0.0071, -0.0098, -0.0303,
         -0.0396,  0.2747, -0.0005,  0.0040,  0.0700,  0.0950, -0.1444, -0.1296,
          0.1522, -0.0639, -0.1318, -0.0365, -0.0138, -0.0695,  0.2868, -0.1195,
         -0.0341, -0.0855, -0.1497, -0.1588,  0.0115,  0.0369,  0.1636, -0.1241,
          0.0337,  0.0477,  0.0704, -0.0366,  0.0050, -0.1107, -0.1432, -0.1101,
         -0.0798, -0.1888,  0.0949,  0.0303, -0.0562,  0.1258,  0.0158, -0.0868,
         -0.0796, -0.1936, -0.0888,  0.0519, -0.2570, -0.0208,  0.2252,  0.2885,
          0.0712, -0.0280,  

In [48]:
for w in 'luca':
    print(w)

l
u
c
a


In [49]:
'luca'.split()

['luca']

In [2]:
import pandas as pd
import numpy as np

In [11]:
df = pd.DataFrame(index=np.arange(0), columns=np.arange(8))

In [9]:
df.iloc[2][3] = 'luca'

In [17]:
l=[[1,2,3,4,5,6], ['0asdlfkalsfdk','1','2','3','4','5']]

In [18]:
pd.DataFrame(l)

0  1  2  3  4  5
0              1  2  3  4  5  6
1  0asdlfkalsfdk  1  2  3  4  5

In [19]:
from smallDatasetGenerator import *
tl = generateDatasetList(10, 10,10)

In [31]:
tl[10]

IndexError: list index out of range